name: vozevida
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  adaptive_screen_flutter: ^0.0.5

  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  easy_localization: ^3.0.1
  flutter_modular: ^5.0.3
  flutter_mobx: ^2.0.6+5
  flutter_signin_button: ^2.0.0
  intro_slider: ^4.2.0
  json_annotation: ^4.7.0
  json_serializable: ^6.5.4
  mobx: ^2.1.3
  shared_preferences: ^2.0.15
  skeletons: ^0.0.3

  carousel_slider: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.3.3
  flutter_lints: ^2.0.0
  # flutter_modular_test: ^1.0.4
  lints: ^2.0.1
  mobx_codegen: ^2.1.1
  slidy: ^4.0.3
  source_gen: ^1.2.6

  flutter_native_splash: ^2.2.17

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/translations/

flutter_native_splash:
  color: "#295DA7"
  image: assets/images/ic_named_logo.png
  android: true
  ios: true
